# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://stemformulas.com"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0
googleAnalytics= "G-055HWG7Q3V"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[imaging]
  resampleFilter = "lanczos"
  quality = 100
