version: '3'
services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    develop:
      watch:
        - action: sync
          path: .
          target: /src/
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"
    develop:
      watch:
        - action: sync
          path: ./streamlit-app.py
          target: /app/streamlit-app.py